### ISSUE TITLE
Cannot instantiate abstract class

### ISSUE THREAD

**Issue by zacharyblank** [coderstephen/edmunds-sdk#1]
Your docs and code don't match up from what I can tell. You have a constructor in an abstract class and you docs say to instantiate that abstract class. Something is missing.

I am happy to submit a PR unless it is me who is missing something.

**Comment by sagebind** [comment]
Oh oops, you're exactly right! That would be my bad. If you're willing to submit a PR, go for it!

Are you interested in using the SDK? I haven't had anyone even look at it much so far. This actually came from a prototype project in PHP. We needed an SDK for PHP, but there wasn't one, so we wrote one in-house. Afterwards, we decided to open-source it. Feel free to suggest any improvements or new features that might be useful if you're interested in using it.

**Comment by connorjburton** [comment]
Ditto on this, the documentation as it stands is incorrect. From what I can see, removing the abstract off `ApiClient` would work? Not sure why it needs to be abstract.

Thanks for making the SDK, it helps!

**Comment by sagebind** [comment]
@connorjburton You can't instantiate `ApiClient` directly since the Edmunds API is actually divided up into multiple different APIs. For example, if you want to use the Vehicle API, you would create an instance of `VehicleApiClient`, which extends `ApiClient`. As of right now, that is the only API implemented, but it wouldn't be too difficult to implement some of the other Edmunds APIs.

As it stands, the documentation is indeed a little confusing on this.

**Comment by connorjburton** [comment]
Okay that makes sense, I guess just removing that section from the documentation is the best bet at the moment then, and just have the `VehicleApiClient` section.
